//Generated by Claude.AI, because of time issues and me not fully understanding back-end concepts yet.
//Still verified to make sense.

// server.js
const express = require('express');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = 3001;

app.use(cors());
app.use(express.json());

const API_BASE = 'https://api.gamblingjamaeglo.dev';
const GAME_SECRET_KEY = process.env.GAME_SECRET_KEY;  // Hidden in .env file

// Fetch wallet endpoint
app.get('/api/wallet/:userId', async (req, res) => {
    try {
        const { userId } = req.params;
        const response = await fetch(`${API_BASE}/portefeuille/utilisateur/${userId}`);

        if (!response.ok) {
            return res.status(response.status).json({ error: 'Failed to fetch wallet' });
        }

        const data = await response.json();
        res.json(data);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

// Transaction endpoint
app.post('/api/transaction', async (req, res) => {
    try {
        const { source, destination, amount } = req.body;

        // Replace source/destination with actual keys
        const actualSource = source === 'GAME' ? GAME_SECRET_KEY : source;
        const actualDestination = destination === 'GAME' ? GAME_SECRET_KEY : destination;

        const payload = {
            source: actualSource,
            destination: actualDestination,
            montant: amount
        };

        const response = await fetch(`${API_BASE}/echangerArgent/${GAME_SECRET_KEY}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorText = await response.text();
            return res.status(response.status).json({ error: errorText });
        }

        const data = await response.json();
        res.json(data);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

app.listen(PORT, () => {
    console.log(`Backend server running on http://localhost:${PORT}`);
});